name: Build OpenWrt

on:
  push:
    branches:
      - master
  workflow_dispatch:
          inputs:
            logLevel:
              description: 'Log level'     
              required: true
              default: 'warning' 
              type: choice
              options:
              - info
              - warning
              - debug 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build OpenWrt
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3.5 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget
          git clone https://github.com/openwrt/openwrt.git
          cd openwrt
          git checkout openwrt-19.07
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make menuconfig
          make -j$(nproc)
