name: Build OpenWrt

on:
  workflow_dispatch:
          inputs:
            logLevel:
              description: 'Log level'     
              required: true
              default: 'warning' 
              type: choice
              options:
              - info
              - warning
              - debug 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Packages
        run: |
          sudo apt-get update
          sudo apt install build-essential clang flex g++ gawk gcc-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget python2
      - name: Clone and checkout
        run: |
          git clone https://github.com/openwrt/openwrt.git
          cd openwrt
          git checkout openwrt-19.07
      - name: Pick config
        run: cp .config openwrt/.config
      - name: Update feeds
        run: cd openwrt && ./scripts/feeds update -a
      - name: Install feeds
        run: cd openwrt && ./scripts/feeds install -a
      - name: Make Openwrt
        run: |
          cd openwrt
          make defconfig
          make -j$(nproc) V=99
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: opewrt-img
          path: |
            openwrt/bin
