name: Build OpenWrt

on:
  workflow_dispatch:
          inputs:
            logLevel:
              description: 'Log level'     
              required: true
              default: 'warning' 
              type: choice
              options:
              - info
              - warning
              - debug 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build OpenWrt
        run: |
          sudo apt-get update
          sudo apt install build-essential clang flex g++ gawk gcc-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget python2
          git clone https://github.com/openwrt/openwrt.git
          cp .config openwrt/.config
          cd openwrt
          git checkout openwrt-19.07
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make -j$(nproc) V=99
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: opewrt-img
          path: |
            openwrt/bin
